"""add status and chunk index

Revision ID: e91124e970e5
Revises: 8766ebd22c98
Create Date: 2026-06-20 16:10:13.750090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91124e970e5'
down_revision: Union[str, Sequence[str], None] = '8766ebd22c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_index', sa.Integer(), nullable=True))
    op.alter_column('chunks', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_chunks_id'), 'chunks', ['id'], unique=False)
    op.add_column('documents', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('documents', 'status')
    op.drop_index(op.f('ix_chunks_id'), table_name='chunks')
    op.alter_column('chunks', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('chunks', 'chunk_index')
    # ### end Alembic commands ###
